# Exercício:

## 01 – Obtenha os resultados e retorne o código em Python dos seguintes cálculos:

In [6]:
a = 2.0 + 3.0 / 5.0

b = (a + 10.2) - 5.0 * 2.0

c =  a / b + 33.8

d = a / (b + c)

e =  d * 2

print(f"a = {a}")
print(f"b = {b}")
print(f"c = {c}")
print(f"d = {d}")
print(f"e = {e}")

a = 2.6
b = 2.799999999999999
c = 34.72857142857143
d = 0.0692805481537876
e = 0.1385610963075752


## 02 – Obtenha os resultados e retorne o código em Python dos seguintes cálculos:

In [8]:
lista_a =  [2.0, 3.0, 5.0] + [10, 20, 30]

lista_a

[2.0, 3.0, 5.0, 10, 20, 30]

In [10]:
lista_b = lista_a * 2

lista_b

[2.0, 3.0, 5.0, 10, 20, 30, 2.0, 3.0, 5.0, 10, 20, 30]

In [12]:
lista_c = lista_a + lista_b

lista_c

[2.0,
 3.0,
 5.0,
 10,
 20,
 30,
 2.0,
 3.0,
 5.0,
 10,
 20,
 30,
 2.0,
 3.0,
 5.0,
 10,
 20,
 30]

In [16]:
lista_d = lista_a / (lista_b * lista_c)

# ERRO: não tem como multiplicar uma lista por um não int (ex: 2)

TypeError: can't multiply sequence by non-int of type 'list'

## 03 – Usando os objetos simples obtidos no exercício 01, instancie uma  lista. Instancie também uma segunda lista contendo a raiz quadrada dos valores obtidos nos objetos simples. Instancie uma terceira lista, concatenando as duas primeiras. Recupere a última lista.

In [20]:
lista = [a, b, c, d, e]

lista_raiz = [
    a**0.5,
    b**0.5,
    c**0.5,
    d**0.5,
    e**0.5,
              ]

lista_concatenada = lista + lista_raiz

lista_concatenada

[2.6,
 2.799999999999999,
 34.72857142857143,
 0.0692805481537876,
 0.1385610963075752,
 1.61245154965971,
 1.6733200530681507,
 5.893095233285427,
 0.263211983302029,
 0.3722379565648501]

## 04 – Duplique os valores contidos na lista final obtida no exercício anterior e converta para um array numpy. Remodele (reshape) o array, para que contenha 5 linhas e 4 colunas. Recupere o array.

In [23]:
lista_duplicada = lista_concatenada * 2

In [ ]:
import numpy as np

array = np.array(lista_duplicada).reshape(5,4)

array

array([[ 2.6       ,  2.8       , 34.72857143,  0.06928055],
       [ 0.1385611 ,  1.61245155,  1.67332005,  5.89309523],
       [ 0.26321198,  0.37223796,  2.6       ,  2.8       ],
       [34.72857143,  0.06928055,  0.1385611 ,  1.61245155],
       [ 1.67332005,  5.89309523,  0.26321198,  0.37223796]])

## 05 – Do array numpy obtenha uma lista contendo a média dos valores de cada uma das colunas.

In [32]:
mean = array.mean(axis=0)
mean

array([7.88073291, 2.14941306, 7.88073291, 2.14941306])

## 06 – O atributo shape pertence ao escopo dos objetos de classe numpy array. Ela retorna uma tupla onde o primeiro valor é o número de linhas e o segundo valor o de colunas contidas no array. Usando a informação do número total de valores presentes no numpy array do exercício 4 insira neste array a lista obtida no exercício 5. Recupere o array.
Obs.:  Atributos não usam () na chamada.

In [36]:
novo_array = np.vstack([array, mean])

novo_array

array([[ 2.6       ,  2.8       , 34.72857143,  0.06928055],
       [ 0.1385611 ,  1.61245155,  1.67332005,  5.89309523],
       [ 0.26321198,  0.37223796,  2.6       ,  2.8       ],
       [34.72857143,  0.06928055,  0.1385611 ,  1.61245155],
       [ 1.67332005,  5.89309523,  0.26321198,  0.37223796],
       [ 7.88073291,  2.14941306,  7.88073291,  2.14941306]])

## 07 – Remodele (reshape) o array do exercício anterior, para que contenha 4 colunas. Converta este objeto da classe array para DataFrame. Arredonde todos os valores para até 3 casas decimais. Recupere a DataFrame.

In [43]:
novo_array = novo_array.reshape(-1,4) #ja era antes

import pandas as pd

df = pd.DataFrame(novo_array)
df

,0,1,2,3
0,2.600000,2.800000,34.728571,0.069281
1,0.138561,1.612452,1.673320,5.893095
2,0.263212,0.372238,2.600000,2.800000
3,34.728571,0.069281,0.138561,1.612452
4,1.673320,5.893095,0.263212,0.372238
5,7.880733,2.149413,7.880733,2.149413


In [47]:
df = df.round(3)
df

,0,1,2,3
0,2.600,2.800,34.729,0.069
1,0.139,1.612,1.673,5.893
2,0.263,0.372,2.600,2.800
3,34.729,0.069,0.139,1.612
4,1.673,5.893,0.263,0.372
5,7.881,2.149,7.881,2.149


## 08 – A última instancia desta DataFrame deve conter as médias dos valores contidos por coluna, o que foi determinado nos exercícios anteriores. Instancie um objeto contendo as médias dos valores em cada linha. Insira este objeto como uma nova coluna na DataFrame. Recupere a DataFrame.

In [58]:
#medias = medias dos valores em cada linha
media_linhas = df.mean(axis=1).to_list()

#inserir medias como nova coluna na data frmae
df['media_linhas'] = media_linhas
df

,0,1,2,3,media_linhas
0,2.600,2.800,34.729,0.069,10.04950
1,0.139,1.612,1.673,5.893,2.32925
2,0.263,0.372,2.600,2.800,1.50875
3,34.729,0.069,0.139,1.612,9.13725
4,1.673,5.893,0.263,0.372,2.05025
5,7.881,2.149,7.881,2.149,5.01500


## 09 – Usando o método dos objetos de classe DataFrame, describe(), compare os resultados contidos na última linha e última coluna da DataFrame.

Obs.: O método dos objetos de classe DataFrame, transpose(), inverte linhas por colunas.

In [74]:
#describe dos itens da ultima coluna
df_described = df['media_linhas'].describe()
df_described

count     6.000000
mean      5.015000
std       3.758615
min       1.508750
25%       2.120000
50%       3.672125
75%       8.106688
max      10.049500
Name: media_linhas, dtype: float64

In [81]:
#df.describe(df['media_linhas'])
df_transposto = df.transpose()

df_transposto[5].describe()

count    5.000
mean     5.015
std      2.866
min      2.149
25%      2.149
50%      5.015
75%      7.881
max      7.881
Name: 5, dtype: float64

## 10 – Edite o nome das colunas e dos index, para indicar onde estão as médias. Qual a média das médias?

In [85]:
# renomear a ultima linha (index 5)
df = df.rename(index={
    5: "media_colunas"
})

df

,0,1,2,3,media_linhas
0,2.600,2.800,34.729,0.069,10.04950
1,0.139,1.612,1.673,5.893,2.32925
2,0.263,0.372,2.600,2.800,1.50875
3,34.729,0.069,0.139,1.612,9.13725
4,1.673,5.893,0.263,0.372,2.05025
media_colunas,7.881,2.149,7.881,2.149,5.01500


In [101]:
# Média das médias
df.iloc[-1, -1]

np.float64(5.015000000000001)